### ISSUE TITLE
Hands are not clear

### ISSUE THREAD

**Issue by donaldchi999** [GamesThatWork/BrushUpBuilds#1]
**Is your feature request related to a problem? Please describe.**

On the screen where you sign up users, I don’t understand the hands - you may want to include a R and L over the hands to indicate handedness

**Describe the solution you'd like**
A clear and concise description of what you want to happen. Look

**Describe alternatives you've considered**

**Additional context**

**Comment by DovJacobson** [comment]
I thought it was obvious -- but of course -- everybody on our team knew what it meant before it was created!!

**Comment by DovJacobson** [comment]
I believe this is self explanatory now

@ernstc2 if this cures this issue please CLOSE it
