### ISSUE TITLE
Delay in play and toothbrushing

### ISSUE THREAD

**Issue by dnemaw** [GamesThatWork/BrushUpBuilds#10]
There is a delay of about 4-5 sec after pressing play till Budd starts toothbrushing

**Comment by DovJacobson** [comment]
I need more description of this problem, please:
- Is Budd visible?
- Is Budd frozen? 
- Is Budd audible?
Screenshot please?

**Comment by dnemaw** [comment]
I didn't observe the delay in the new version v0.442

**Comment by DovJacobson** [comment]
I will close this for you Deeksha, but better if you do
