### ISSUE TITLE
Screen mirror

### ISSUE THREAD

**Issue by dnemaw** [GamesThatWork/BrushUpBuilds#12]
There is a delay for the screen mirror to show our image after we enter the toothbrushing section even after allowing camera access.
I had to touch it a couple times to ensure it captures me.

**Comment by DovJacobson** [comment]
@jon-dameron 
please cure this issue by removing the scary looking [NO CAMERA DETECTED] texture that displays on the mirror during camera warm up.

**Comment by DovJacobson** [comment]
@dnemaw thanks for reporting this but it is a minor cosmetic issue
it is low priority, and we do not expect it to impede deployment

**Comment by DovJacobson** [comment]
This cosmetic improvement might take a day or two
and it is nt worth delaying RELEASE 444 deployment.
