### ISSUE TITLE
Sound/Ringer

### ISSUE THREAD

**Issue by dnemaw** [GamesThatWork/BrushUpBuilds#14]
If the ringer/sound switch on the iPhone is turned off or is in silent mode, users will not be able to hear audio in the app. 
We want the audio to be audible even when the ringer is turned off.

If not, we need instructions for users to turn on the ringer when using the app.

**Comment by DovJacobson** [comment]
a rewritten audio system might eliminate this problem
and if not, we have a method to detect the lock and warn the player

@dnemaw @ernstc2 
please test version 442 
if this still does not work please use this probe
https://bu-pwa.web.app/silentmode.html

to see which (if any) of the four options can be heard wit the lock engaged
(please reload url between tests)


if iti s cured in 0442 please close this issue

**Comment by ernstc2** [comment]
fixed, but caused issue 22
