### ISSUE TITLE
App froze in virtual bathroom

### ISSUE THREAD

**Issue by dnemaw** [GamesThatWork/BrushUpBuilds#15]
The app froze when I was done with match game and ready to buy prizes. I couldn't tap anywhere on the screen.

**Comment by DovJacobson** [comment]
cannot easily reproduce
v0.442 has changes that are intended to cure the issue
@dnemaw if it is now fixed please close
@ernstc2 please check if you can and close if you can

**Comment by ernstc2** [comment]
seems to be cured, feel free to re-open if further related problems occur.
