### ISSUE TITLE
Notification bell

### ISSUE THREAD

**Issue by dnemaw** [GamesThatWork/BrushUpBuilds#16]
Iphone notification bells rings every 30-40 sec after starting the app

**Comment by DovJacobson** [comment]
Please be sure that this is truly the Notification system of the app. (This was suppressed after 433, I believe). 
--Or are you hearing that our [ DING sound effect](https://bu-pwa.web.app/content/audio/ding.mp3) that perhaps sounds too much like the Notification tone on iPhone or Chrome?

**Comment by DovJacobson** [comment]
New assets added to cure problem

@dnemaw @ernstc2 
Please verify that this issue is cured in v0.442
If so, please CLOSE it

**Comment by ernstc2** [comment]
This issue seems to still be a problem in the current BUILD 0.442.
Specifically, when in the main brushing mode with BUZZ, I'm experiencing both the notification sound and now a new "pop" like sound pretty regularly.

Will specifically talk to Dov about this issue.

**Comment by DovJacobson** [comment]
chris tested this with me 
cured in 443
