### ISSUE TITLE
App freeze 3/28 

### ISSUE THREAD

**Issue by dnemaw** [GamesThatWork/BrushUpBuilds#17]
Iphone 14, ios 17.3.1
The app froze after opening and continued to be frozen for a few minutes before I X'ed out entirely on my phone. 
Attempted to restart the app but froze again. 

![MicrosoftTeams-image (6)](https://github.com/GamesThatWork/BrushUpBuilds/assets/161871167/10ee6cc5-5398-43e3-9279-1f0d86e44795)

**Comment by ernstc2** [comment]
Did this problem keep occurring after re-attempts to put into portrait mode and then back to landscape?
Had this happen to me as well, but was able to "fix" it by adjusting to and from the different modes.

**Comment by dnemaw** [comment]
My screen is kindof stuck to this even now. By default, the app opens to the screen I attached in my previous comment. 
I turned off the portrait orientation lock and it helps a bit to re-orient the app.

**Comment by ernstc2** [comment]
I see what you mean about the iPhone's orientation lock, currently, things do freeze up like you said when you have the lock on, when off the fix for this is simply holding your phone to the side (landscape mode) and letting the app about correct itself orientation wise. let me know if this temporary fix works for you, we can address this issue later with Dov.

**Comment by DovJacobson** [comment]
the problem here is that the phone is locked to portrait, so rotating the phone in order to orient it correctly will have no effect. It is locked.

I did not anticipate this problem. I hope we can detect it and (as necessary) tell user to unlock the phone orientation.

**Comment by dnemaw** [comment]
Turning off the orientation lock works for me now. I believe that needs to be done before opening the app. 
Because the starting screen of the app is still the same.

**Comment by DovJacobson** [comment]
please test Build 0.438 which addresses this freeze
it should fix the problem

438 is live  at  https://bu-pwa.web.app/

**Comment by DovJacobson** [comment]
If it is cured, PLEASE close this issue!
