### ISSUE TITLE
Brush Game auto-Complete

### ISSUE THREAD

**Issue by ernstc2** [GamesThatWork/BrushUpBuilds#18]
**Describe the bug**
When playing the brushing game with Bud, if you at any point pause the game and keep the game paused eventually the game will conclude. As soon as I noticed I was able to, I paused the brushing game with Bud, and about 4-5 minutes later (the duration of the brushing game) the game ended and put me on the match and win points screen.

**To Reproduce**
1. Go to brushing game with bud
2. pause at any point in the game
3. wait
4. eventually you will come to the match and win points screen

**Expected behavior**
When pausing, the game timer should also pause, allowing the full game to be played after un-pasuing.

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [0.436]

**Additional context**
This bug also works on the same build on iPhone 11, seems to be a bug in code and not a user device issue.

**Comment by DovJacobson** [comment]
I have identified the problem code and will fix after higher priority issues

**Comment by DovJacobson** [comment]
Much harder to fix than I anticipated, but now the system is actually cleaner and functions better.



@ernstc2 
Please verify that this issue is cured in v0.442
If so, please CLOSE it
