### ISSUE TITLE
Default Match and Win Points screen

### ISSUE THREAD

**Issue by ernstc2** [GamesThatWork/BrushUpBuilds#19]
**Describe the bug**
After a game is complete with Bud, at the match and win points screen you are always met with a blank middle picture and all lower 3 pictures are Earth rotating. Nothing can be done by the user until the points button is clicked or a world is selected, which then starts the actual match game.

**To Reproduce**
1. Complete a game with bud

**Expected behavior**
I think this screen with the Earths is confusing for the user, instead of forcing the user to select a world to start the game, maybe an auto start or a specific start match game would be appropriate.

**Screenshots**
![matchscreen](https://github.com/GamesThatWork/BrushUpBuilds/assets/112519347/ea257653-6325-4ef7-8c01-b1ece5c1891e)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Chrome]
 - Version [BUILD 0.436]

**Smartphone (please complete the following information):**
 - Device: [iPhone 11]
 - OS: [IOS 17.3.1]
 - Browser [Chrome]
 - Version [BUILD 0.436]

**Additional context**
This happened on both Windows 10 and iPhone 11 on BUILD 0.436.
Not sure if this is a bug or is intended, so I apologize if this issue is labeled incorrectly.

**Comment by DovJacobson** [comment]
@ernstc2  
This report asserts that the issue occurs **_always_**.
Not true.  

Please distinguish with absolutely sharpness the difference between the conditions when it occurs and when it does not. (As you have done with great success on other issues.)

This distinction is _extremely_ valuable information!!
