### ISSUE TITLE
Is this web based now? 

### ISSUE THREAD

**Issue by donaldchi999** [GamesThatWork/BrushUpBuilds#2]
**Is your feature request related to a problem? Please describe.**

I followed the link and it appears to be a webpage and not an app

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by donaldchi999** [comment]
Ah - I got it to launch an app. The institutions to parents needs to include a line about opening the link in safari. I was using chrome

**Comment by DovJacobson** [comment]
Thanks -- It is supposed to pop up a message that advises you to switch from chrome to safair if you are on iPhone (Apple requirement -- sigh). That message used to happen earlyt but now it is later.

**Comment by DovJacobson** [comment]
It has an instruction and illustration when needed in iPhone, Android and Computer


@ernstc2:  If this issue is now cured,  please CLOSE it
