### ISSUE TITLE
Shop points Values Inconsistent 

### ISSUE THREAD

**Issue by ernstc2** [GamesThatWork/BrushUpBuilds#20]
**Describe the bug**
Below are 3 screenshots, two are of the Dinosaur theme and one from the fish theme. When in the shop to use points from games, if you change between them to another then back to the first theme different values of cost for the items available show. The first screenshot below shows the "Toy Rex" initially being 7 points, but after switching themes and coming back, the other screenshot shows the same toy now being 6 points. This bug can be repeated until a prize shows an amount desired which seems incorrect.

**To Reproduce**
1. Go to a theme in a shop and notice the price for a prize
2. Click on a different theme
3. Go back to the original theme 
4. See the change in prize price

**Expected behavior**
Prize prices should always be consistent and be worth a pre-determined value that never changes. which would give a child incentive to save up for a prize to work towards.

**Screenshots**
![Before](https://github.com/GamesThatWork/BrushUpBuilds/assets/112519347/a2c0581d-690c-40bf-9eb9-65b7b71ed340)
![change to another](https://github.com/GamesThatWork/BrushUpBuilds/assets/112519347/703afea8-23e5-4ea3-9932-293493db2c58)
![after](https://github.com/GamesThatWork/BrushUpBuilds/assets/112519347/44096f65-a3c0-49ff-aae7-7e3f3cb9dc6a)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [BUILD 0.436]

**Smartphone (please complete the following information):**
 - Device: [Iphone 11]
 - OS: [iOS17.3.1]
 - Browser [Chrome]
 - Version [BUILD 0.436]

**Additional context**
This worked with both Windows 10 and iPhone 11 on the same build.
SOME VALUES OF PRIZES NEVER CHANGE

**Comment by DovJacobson** [comment]
@ernstc2 @jon-dameron 
This will be fixed by new prize models rom Jon

**Comment by DovJacobson** [comment]
@ernstc2 
in the interim (waiting for new models from Jon) I have stabilized the prices so they are no longer a slot machine :(

Please verify that this issue is (crudely, & hopefully temporarily) cured in v0.442   If 'cured', please change title to 'Shop shows Placeholder Prices"

**Comment by DovJacobson** [comment]
chris tested this with me
cured in 443
