### ISSUE TITLE
Locked out of shop

### ISSUE THREAD

**Issue by ernstc2** [GamesThatWork/BrushUpBuilds#21]
**Describe the bug**
when going to shop to redeem prizes, currently defaults to picture 1 linked below. upon clicking on any themes, I am shown picture 2 linked below. If the user then clicks the same theme again, they are met with a picture similar to picture 1 shown in picture 3 below. This results in being locked out from making purchases for prizes. Currently, if the user does click the link from the lock screen (picture 2), then the user is directed to "https://bu-pwa.web.app/index.html?join=account&open=price" which as shown in picture 4, is just the home screen. Was something changed? seems like a new screen I haven't seen before.

**To Reproduce**
1. Go to the Prizes shop
2. Click on any theme
3. To see just the lock screen (picture 3) click the same theme again

**Expected behavior**
The text shouldn't disappear for the user after clicking the same theme again. 
Restrictions don't seem to be operating as intended.

**Screenshots**
![1](https://github.com/GamesThatWork/BrushUpBuilds/assets/112519347/5c49304c-3935-47f9-8d26-57bb201afb57)
![2](https://github.com/GamesThatWork/BrushUpBuilds/assets/112519347/85353fe7-3152-4d3b-9d84-a3d7a74ba7ff)
![3](https://github.com/GamesThatWork/BrushUpBuilds/assets/112519347/4c71d2c3-a7c4-4224-880f-17e8f7ed2c66)
![4](https://github.com/GamesThatWork/BrushUpBuilds/assets/112519347/9a896b4c-da22-45e7-8de9-8dcaef8a7f88)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [BUILD 0.442]

**Additional context**
Even after going into "family" and clicking on the paid subscription option, I remained locked out of the shop to unlock prizes.

**Comment by DovJacobson** [comment]
chris tested this with me
cured in 443
