### ISSUE TITLE
Ringer text bubble incorrectly showing

### ISSUE THREAD

**Issue by ernstc2** [GamesThatWork/BrushUpBuilds#22]
**Describe the bug**
When in the phone app, when pressing buttons, or sometimes randomly even when the ringer is off (audio is not being suppressed) the user will still receive "Your divide is suppressing audio. Is it in "Do Not Disturb" mode?". 

**To Reproduce**
1. Have the ringer off 
2. click on buttons within the mobile app home screen

**Expected behavior**
This message would hopefully only appear when the ringer function is on (actually suppressing audio).

**Screenshots**
![IMG_6335](https://github.com/GamesThatWork/BrushUpBuilds/assets/112519347/b4e72772-1263-4455-bc78-88ad8b7e128c)

**Smartphone (please complete the following information):**
 - Device: [Iphone 11]
 - OS: [iOS17.3.1]
 - Browser [Chrome]
 - Version [BUILD 0.442]

**Comment by DovJacobson** [comment]
chris tested this with me
cured in 443
