### ISSUE TITLE
On app start audio failure

### ISSUE THREAD

**Issue by ernstc2** [GamesThatWork/BrushUpBuilds#23]
**Describe the bug**
The typical sounds that play when starting up the app aren't functioning properly. Sometimes skipping the audio altogether.

**To Reproduce**
1. go to app home (index page works)
2. listen for typical app start-up sound
3. refresh the page to hear it over again

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [BUILD 0.442]

**Additional context**
This problem wasn't consistent, sometimes would work as intended and other times wouldn't, couldn't figure out what caused it.

**Comment by DovJacobson** [comment]
It is unclear to me whether you are simply disturbed by recent changes to the sound design
or whether this is a minor bug

In either case, this issue is not worth delaying RELEASE 444 deployment.
