### ISSUE TITLE
Home Missing Text

### ISSUE THREAD

**Issue by ernstc2** [GamesThatWork/BrushUpBuilds#24]
**Describe the bug**
After going to the account information (Our family) pages and clicking the "done" button the user will return to the home screen but without any logo or text. 

**To Reproduce**
1. Go to "Our family"
2. Click on "done" button
3. See irregular home screen

**Expected behavior**
The user should be returned to the home screen with the text still there.

**Screenshots**
![homewithnotext](https://github.com/GamesThatWork/BrushUpBuilds/assets/112519347/68f7f948-66ca-4fb3-9389-ac9170d50afc)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [BUILD 0.442]

**Additional context**
seems to still be on the website default page, after clicking done the user returns to this no-text screen at "https://bu-pwa.web.app/"

upon refreshing the text re-appears.

**Comment by DovJacobson** [comment]
This is an (apparently unsuccessful) design decision.
The entire onboarding flow needs to be reimagined, 
but that process might be protracted and 
it is not worth delaying RELEASE 444 deployment.

**Comment by ernstc2** [comment]
issue on private repo
