### ISSUE TITLE
Needs instructions and pause button

### ISSUE THREAD

**Issue by donaldchi999** [GamesThatWork/BrushUpBuilds#3]
**Is your feature request related to a problem? Please describe.**

 There are lots of places where I'm confused about what is going on / I didn't realize I had to have my phone in landscape.

Is it possible to insert a pause button? 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by DovJacobson** [comment]
1: The app now has code that is supposed to lock it to landscape orientation - but it doesn't work well, does it?

2: Pause is a good idea -- (also more consistent with the commercial build)

**Comment by DovJacobson** [comment]
Pause and Force-to-Landscape are added
  (both led to _new_  issues)

@ernstc2 if this cures the issue please close
