### ISSUE TITLE
Multiple users, wrong shop

### ISSUE THREAD

**Issue by ernstc2** [GamesThatWork/BrushUpBuilds#30]
**Describe the bug**
When having multiple users, clicking on the home screen's shop button for one user is redirecting me to the other users shop.
For example, with two users, A and B, if clicked on users A shop, the user will go to user's B shop. And when clicking on user's B shop will go to User's B shop. 

Picture 1 leads to picture 2, picture 3 leads to picture 4 below.

**To Reproduce**
1. Have multiple users
2. Click on shops for both
3. See shop for only one user

**Expected behavior**
Shop button should redirect user to corresponding user's shop.

**Screenshots**
![1](https://github.com/GamesThatWork/BrushUpBuilds/assets/112519347/a9e24387-0c27-4276-b906-f405262377f7)
![2](https://github.com/GamesThatWork/BrushUpBuilds/assets/112519347/fd54b0a5-a3f9-4bef-854a-c7744cac1c85)
![Capture](https://github.com/GamesThatWork/BrushUpBuilds/assets/112519347/7093c977-2bac-4f49-9ed8-466b19095693)
![4](https://github.com/GamesThatWork/BrushUpBuilds/assets/112519347/0a9ab43f-4341-42df-8638-c675a0c16c3a)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [BUILD 0.444a]

**Additional context**
Because the shop always defaults to User's B shop, the issue might be related to precedence of when the users were made (unsure).

**Comment by ernstc2** [comment]
Found out that this is determined by whichever user profile was updated last. So, to change which shop shows, make an update to the user profile you want to show.

Hope this helps to better understand the coding origin of this issue.

**Comment by ernstc2** [comment]
You were completely right, as shown below in the screenshots, the user last changed is made brushed 0 and is the one sent to shop.  

Before change
![1](https://github.com/GamesThatWork/BrushUpBuilds/assets/112519347/3ce891a5-7618-4efa-8c37-7161e4c3a601)
![2](https://github.com/GamesThatWork/BrushUpBuilds/assets/112519347/c4df73b4-8212-4c7c-b75d-84614e2aec07)

after change
![3](https://github.com/GamesThatWork/BrushUpBuilds/assets/112519347/db60af65-ecd8-4c0f-a643-8bd5cea582fb)
![4](https://github.com/GamesThatWork/BrushUpBuilds/assets/112519347/58de5bd9-cac1-4bfd-9d09-f65a55f96554)

**Comment by DovJacobson** [comment]
fixed in 460
