### ISSUE TITLE
Rooms overlap

### ISSUE THREAD

**Issue by ernstc2** [GamesThatWork/BrushUpBuilds#31]
**Describe the bug**
When in the shop, the user sees rooms overlapping with each other giving the impression rooms are incorrectly labeled.
See screenshot below.

**To Reproduce**
1. Go to shop
2. See overlap

**Expected behavior**
all rooms should have correct spacing.

**Screenshots**
![overlap](https://github.com/GamesThatWork/BrushUpBuilds/assets/112519347/81df4df5-6be5-4a43-8414-20ea8dde899b)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [BUILD 0.444a]

**Additional context**
As tested with Dov, the bug might be dependent on resolution and even the windows version.

**Comment by ernstc2** [comment]
Bug might be related: Black areas under rooms and above themes

**Comment by DovJacobson** [comment]
@ernstc2 check build 446

**Comment by ernstc2** [comment]
fixed with build 446 on test server
