### ISSUE TITLE
Slots in strange places

### ISSUE THREAD

**Issue by ernstc2** [GamesThatWork/BrushUpBuilds#33]
**Describe the bug**
Within the store, certain rooms and themes display all slots in the same place, unfortunately due to the current placement of the 3D models looks strange and borderline confusing for potential users. This is most apparent in the room Egypt and miniworld.

**To Reproduce**
1. Go to shop
2. Click on either Egypt themes or mini-world themes
3. See slots not aligned with items

**Expected behavior**
Slots should be at least near the items being bought by the user

**Screenshots**
![miniworldbaseball](https://github.com/GamesThatWork/BrushUpBuilds/assets/112519347/5aec84bd-a874-464b-8403-159498068f72)
![Egypt](https://github.com/GamesThatWork/BrushUpBuilds/assets/112519347/1971cbdd-096a-45f1-939e-755557cc02ea)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [BUILD 0.444a]

**Comment by ernstc2** [comment]
Currently, in build 0.454, I found the image below which shows slots in the mini world to appear in places they are not meant to. This wasn't like this before when I originally made this issue which makes me think this might be a separate problem and therefore a separate issue, however, it fits this issue. See below.

![1](https://github.com/GamesThatWork/BrushUpBuilds/assets/112519347/fb0096de-3dfc-4130-a4e1-109679ead4f4)

**Comment by DovJacobson** [comment]
@ernstc2 please try to identify the common principle.

To me it sounds like the Price Locations, which vary from Room to Room but are the same from Theme to Theme within a Room are incorrect in Egypt and in Small World, but in those two worlds, they are wrong in different ways.

**Comment by ernstc2** [comment]
issue on private repo
