### ISSUE TITLE
Equipping Rooms

### ISSUE THREAD

**Issue by ernstc2** [GamesThatWork/BrushUpBuilds#34]
**Describe the bug**
On the current Build 444a, I cant even seem to find the feature to equip other rooms, perhaps its not even implemented yet. If it is, its not clear to the user.

**To Reproduce**
1. Go to store
2. click on the room the user wants
3. confusion

**Expected behavior**
Maybe a button is needed to equip the rooms or easier to find for the user.

**Screenshots**
![how do i equip small world](https://github.com/GamesThatWork/BrushUpBuilds/assets/112519347/4385936b-cace-4206-86fe-6452222eda2c)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [BUILD 0.444a]

**Comment by DovJacobson** [comment]
i do not understand what it means to "Equip" a room.
Explain please.

**Comment by ernstc2** [comment]
Simply if a user wants to use a room for the brushing game with Bud, other than the starter room. Egypt for example.

**Comment by DovJacobson** [comment]
ok i see

The design is simply that you will play each time in the room you most
recently visited in the Prize Shop

Is this not working  -- or is it unclear?

**Comment by ernstc2** [comment]
Both unclear and not working
