### ISSUE TITLE
Egypt Anubis Item

### ISSUE THREAD

**Issue by ernstc2** [GamesThatWork/BrushUpBuilds#35]
**Describe the bug**
A particular item in the Egypt room behaves really strangely after just a simple "inspect" to consider buying. After clicking to inspect the item doesn't even show its 'wobble" animation and after the item unexpectedly gets massive.

**To Reproduce**
1. Go to Egypt in shop
2. Click on "Anubis" item
3. see lack of item for "inspect"
4. click off
5. see growth in size

**Expected behavior**
Item should be displayed properly when considering to buy and should remain same size after.

**Screenshots**
![1](https://github.com/GamesThatWork/BrushUpBuilds/assets/112519347/b745ccbd-1cc9-4276-8660-5886ba3618a5)
![2](https://github.com/GamesThatWork/BrushUpBuilds/assets/112519347/44891e04-e3ec-4183-a38e-10cc2c0dd1a0)
![3](https://github.com/GamesThatWork/BrushUpBuilds/assets/112519347/7c99ac57-03f8-435d-965a-d8c140b148bd)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [BUILD 0.444a]

**Comment by DovJacobson** [comment]
wow 
good bug catch
but this is almost certainly an issue of content flaw
and so should be assigned to @jon-dameron

**Comment by ernstc2** [comment]
issue on private repo
