### ISSUE TITLE
Slider

### ISSUE THREAD

**Issue by ernstc2** [GamesThatWork/BrushUpBuilds#39]
**Describe the bug**
In the shop, the slider for selecting rooms simply just dont act like the user would expect, sometimes sliding upwards when you'd expect it to go downwards. For example, if a user clicks a room above on the slider one would expect the slider to always slide down, however, this doesn't always happen. 

**To Reproduce**
1. click on shop
2. click rooms above the starter
3. see slide upwards

**Expected behavior**
the slider should basically always slide downwards because that's all the user can see.

**Screenshots**
![1](https://github.com/GamesThatWork/BrushUpBuilds/assets/112519347/8bb12b86-1231-4289-a114-f3fb67b4ac0e)
![2](https://github.com/GamesThatWork/BrushUpBuilds/assets/112519347/6e0526cd-6af0-484f-9bdc-9950541150f4)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [BUILD 0.444a]

**Additional context**
We are already well aware of this issue and possible solutions, the issue was made for documentation.

**Comment by DovJacobson** [comment]
Pleas hold and see if fixed with setsize fix v447

**Comment by DovJacobson** [comment]
thx!!
