### ISSUE TITLE
Stuck in match game room after first brushing

### ISSUE THREAD

**Issue by donaldchi999** [GamesThatWork/BrushUpBuilds#4]
**Describe the bug**

I can’t seem to get out of the match game room after playing the match game

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by DovJacobson** [comment]
Fixed long ago, but has it reappeared?

@ernstc2:  If this issue is now cured,  please CLOSE it

**Comment by ernstc2** [comment]
seems to have been cured, if anything comes up, feel free to re-open
