### ISSUE TITLE
Prize names

### ISSUE THREAD

**Issue by ernstc2** [GamesThatWork/BrushUpBuilds#40]
**Describe the bug**
Prize names are unclear, too long, not consistent with other names, or incorrect. List below.

Prizes in the list will be shown by:
(room)-(theme)-(Item)

List:
(starter)-(1)-("Steggy Boy")
(starter)-(1)-("Dino Parade Shower curtain")
(starter)-(2)-("FishTowelGeo")
(starter)-(2)-("Sink on Porpise")
(starter)-(2)-("Royal Goldfish Shower Curtain")
(starter)-(3)-("ShapesTowelGeo")
(starter)-(3)-("Tessellation Curtain")
(starter)-(3)-("Bathtub Blowup Toy")
(starter)-(4)-("Buffy Doll")
(starter)-(5)-("Checkered Flag Shower Curtain")
(room 4)-(ALL)-(ALL)

**To Reproduce**
1. go to shop
2. see prize names

**Expected behavior**
Prize names should be short and to the point.

**Screenshots**
![1](https://github.com/GamesThatWork/BrushUpBuilds/assets/112519347/1d34f236-9427-4adc-9041-2b86900b33d0)
![2](https://github.com/GamesThatWork/BrushUpBuilds/assets/112519347/faefd22b-1fb6-4c3c-9259-5dfe0b092f8a)
![3](https://github.com/GamesThatWork/BrushUpBuilds/assets/112519347/947b1950-6ab4-48ab-bf60-e6c11ac500a9)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [BUILD 0.445]

**Additional context**
-(NOTICE) For room 4, all themes have "Mini:" before the prize names, that's why in the list of items "ALL" is used.
-Some item's names are objectively correct/okay but when placed near others that are significantly different it doesn't look right, refer to screenshot 3.
-Examples are shown in screenshots, for all problem items, refer to the list above.
-There is some consideration to completely remove names altogether, this issue is made not in this consideration.

**Comment by DovJacobson** [comment]
@ernstc2  -oops 

some of these were meant to be funny
_"Sink on Porpise"_

or friendly
_"Steggy Boy"_

or simply descriptive
_"Buffy Doll"_

**Comment by ernstc2** [comment]
issue on private repo
