### ISSUE TITLE
Missing Profile Icons

### ISSUE THREAD

**Issue by ernstc2** [GamesThatWork/BrushUpBuilds#42]
**Describe the bug**
Currently, on build 0.445, I'm missing icons in the edit profiles screen, as seen below in the screenshot all icons for left vs right-handed, and deletion icons are missing. Not sure if there is a prerequisite to activate this bug, but even after a hard reset on the app the icons won't re-appear. Tried to replicate this on deployed version 0.444a and could not replicate it, might be a 0.445 issue.

**To Reproduce**
1. Go to family
2. Click on profiles
3. Click on a profile
4. See missing icons

**Expected behavior**
Icons should be present.

**Screenshots**
![1](https://github.com/GamesThatWork/BrushUpBuilds/assets/112519347/8fee5f7d-f69a-44d6-9a99-6d589c9f642e)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [BUILD 0.445]

**Additional context**
Again, could only see this bug on build 0.445 and not 0.444a

**Comment by ernstc2** [comment]
This issue is confirmed as a result of GitHub repository problems in recent events, not a problem in 0.444a. 

When 0.4446 is launched (assuming all Github problems are gone) I will close this issue.

**Comment by DovJacobson** [comment]
@ernst excellent!

**Comment by ernstc2** [comment]
Fixed in version 0.452
