### ISSUE TITLE
Ghost Profile

### ISSUE THREAD

**Issue by ernstc2** [GamesThatWork/BrushUpBuilds#43]
**Describe the bug**
After deleting a profile, a "ghost" profile will appear but after being clicked on again, will disappear. Below is in order, screenshots of reproducing the bug, notice the pictures, the profile returns but is removed in the following image due to being clicked on. Refer to the reproduction below.

**To Reproduce**
1. Go to profiles
2. Click on create a profile, then delete said profile
3. Seems normal, but click the screen again
4. See "ghost" profile
5. click on the ghost profile
6. see profile disappear

**Expected behavior**
After deletion, a profile should never be seen again

**Screenshots**
![1 normal](https://github.com/GamesThatWork/BrushUpBuilds/assets/112519347/37afeea0-809c-4b15-b986-09d677646ad3)
![2 made extra](https://github.com/GamesThatWork/BrushUpBuilds/assets/112519347/c3eb0022-80f3-4459-9a7b-317e0b62f82c)
![deletiing](https://github.com/GamesThatWork/BrushUpBuilds/assets/112519347/ec2f047e-894d-4f6c-ba3c-82fb03a21443)
![4 looks fine](https://github.com/GamesThatWork/BrushUpBuilds/assets/112519347/b60800c8-455c-4ea8-b006-61bdf3d31eca)
![5 back](https://github.com/GamesThatWork/BrushUpBuilds/assets/112519347/21503199-1626-4310-a433-6b8d9a68c99c)
![final](https://github.com/GamesThatWork/BrushUpBuilds/assets/112519347/a2c386a9-dfda-43ea-a553-422f2c55dfea)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [BUILD 0.445]

**Comment by ernstc2** [comment]
Please note, as discussed in issue #42 icons are missing, this bug is a separate issue. Literally.

**Comment by DovJacobson** [comment]
@ernstc2 PLease determine if there is overlap between this Bug and Bug #48

**Comment by ernstc2** [comment]
This is a different problem and therefore a different issue than #48 , I will update #48 with updated rules for replication and specific details soon.

**Comment by ernstc2** [comment]
issue on private repo
