### ISSUE TITLE
Left vs Right Hand Changing

### ISSUE THREAD

**Issue by ernstc2** [GamesThatWork/BrushUpBuilds#46]
**Describe the bug**
While in the edit profile screen, the user is able to change their birthday, name, profile picture, left vs right-handed, and the option to delete their account. However, visually, the user cannot tell that changing the dominant hand is an option due to a bug. When clicking on a different dominant hand there isn't a visual update and the user can't tell anything has changed until they "save" and go into the brushing game with Bud or the shop.

**To Reproduce**
1. Go to the profile edit screen
2. When having multiple profiles, click on the leftmost profile
3. Click on the same profile again
4. See the error lack of visual change when selecting a hand option.

**Expected behavior**

**Screenshots**
![hands](https://github.com/GamesThatWork/BrushUpBuilds/assets/112519347/e969d3a4-0541-4daf-8ab5-17b1d338a037)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [BUILD 0.445]

**Additional context**
In the screenshot above, this screen is what is shown after the user initially signs up as right-handed but then selects left-handed in the profile edit, as you can see even though the user has selected left, no change has visually been made.

**Comment by ernstc2** [comment]
This bug is more complicated than initially thought, will update soon with the replication method

**Comment by DovJacobson** [comment]
Good clear write-up

**Comment by ernstc2** [comment]
When having 2 accounts, this bug always occurs to the rightmost account and doesn't occur to the leftmost account. However, the positions of the accounts can be changed through a series of selections of the accounts resulting in the bug being capable of affecting all accounts (the first sentence stays true).

**Comment by DovJacobson** [comment]
@ernstc2 - please determine whether this linked to Brusher[0] in the LocalStorage data

**Comment by ernstc2** [comment]
You were completely right, as shown below in the screenshots, the user last changed is made brushed 0 and is the one sent to shop.  

Before change
![1](https://github.com/GamesThatWork/BrushUpBuilds/assets/112519347/3ce891a5-7618-4efa-8c37-7161e4c3a601)
![2](https://github.com/GamesThatWork/BrushUpBuilds/assets/112519347/c4df73b4-8212-4c7c-b75d-84614e2aec07)

after change
![3](https://github.com/GamesThatWork/BrushUpBuilds/assets/112519347/db60af65-ecd8-4c0f-a643-8bd5cea582fb)
![4](https://github.com/GamesThatWork/BrushUpBuilds/assets/112519347/58de5bd9-cac1-4bfd-9d09-f65a55f96554)

**Comment by ernstc2** [comment]
issue on private repo
