### ISSUE TITLE
Moving Profiles

### ISSUE THREAD

**Issue by ernstc2** [GamesThatWork/BrushUpBuilds#48]
**Describe the bug**
When on the edit profiles page, the profiles themselves move around weirdly. For example highlighted in this issue, when clicking on a profile on the left, it will expand but on the right, not where it originally was.

**To Reproduce**
1. Go to Profiles (have multiple)
2. Click on the leftmost one
3. Click off
4. Click on left again
5. See error (mispositioning)

**Expected behavior**
If a left profile is selected, it should expand correctly on the left always.

**Screenshots**
![1](https://github.com/GamesThatWork/BrushUpBuilds/assets/112519347/4124ffd9-48d3-4b48-84c8-b9294fe8a58b)
![2](https://github.com/GamesThatWork/BrushUpBuilds/assets/112519347/946fbf23-8020-41d9-a6f4-3762e79f8df5)
![3](https://github.com/GamesThatWork/BrushUpBuilds/assets/112519347/8751526d-9e80-4188-9291-0d7459333f28)
![4](https://github.com/GamesThatWork/BrushUpBuilds/assets/112519347/944388c2-da32-49e7-a63c-57c4cb4afc13)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [BUILD 0.444a]

**Additional context**
Nothing gets visually distorted, just the potioning gets weird. Screenshots match the replication of the bug, with the first showing the first click, the second image shows normal left expansion, the third shows when the user clicks off, and the fourth shows when the left is clicked again and the bug is present, showing the profile on the right.

**Comment by DovJacobson** [comment]
@ernstc2 the examples you cite are useful, but even better if you can come up with a rule rather than describe the results. A rule might be: The brushers' icons are in age order left to right but the most recently edited is moved to the front"  Probably more complicated thqan this example

**Comment by ernstc2** [comment]
issue on private repo
