### ISSUE TITLE
Points of Contract Checks

### ISSUE THREAD

**Issue by ernstc2** [GamesThatWork/BrushUpBuilds#49]
**Describe the bug**
Currently, the check boxes of the "points of Contract" page within the family button seem to not save, even after pressing done in the bottom right.

*IMPORTANT NOTE" 
This bug also applies in the same way to the "privacy" page, also on the family pages.

**To Reproduce**
1. go to family
2. go to points of contract
3. check/uncheck the boxes
4. press done
5. return back to "Points of Contract"
6. see error / no change

**Expected behavior**
Changes to these checkboxes should be saved, especially after pressing done.

**Screenshots**
![Capture](https://github.com/GamesThatWork/BrushUpBuilds/assets/112519347/c095c823-05ec-43d1-9a9c-10d2bce68162)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [BUILD 0.444a]

**Comment by DovJacobson** [comment]
@ernstc2  Please look at the localStorage to see whether clicking on the checkboxes changes the data saved (so it is the display that is flawed) or if the GUI does not actually change the data. (input system flawed)

**Comment by ernstc2** [comment]
Seems the changed data is never saved, in local storage, all statements never changed boolean values when changing checkboxes.
@DovJacobson
