### ISSUE TITLE
Sign up and account setup

### ISSUE THREAD

**Issue by dnemaw** [GamesThatWork/BrushUpBuilds#5]
I'm unable to sign up to the account and add my gmail.

**Comment by DovJacobson** [comment]
i appreciate your frustration and do not want to add to it,
but let me try to understand enough to address the problem.

iOS 17.3 i think, right?

but 

are you signing up "with google" 
or "with email"

how far does it get?
did y9ou try guest mode or phone mode (just curious)

THANKS

**Comment by dnemaw** [comment]
Hi Dov,

My iphone is iOS 17.3.1.

So, the first time when I tried, I entered as a guest. But then tried to sign in with my gmail, but it didn’t retain my info.
Then I tried to add my account again and haven’t been able to add now.

Today morning,
I just deleted the app from my phone and tried to add to the screen again from the app link. It now gives me an option to sign in using google. But it takes me back to the same page.

I didn’t know I had an option of signing in via phone. I just did, and I’m in the toothbrushing section and works well for me.

Hope that helps. Please let me know if you have further questions.

Thanks,
Deeksha
From: Dov Jacobson ***@***.***>
Date: Friday, March 1, 2024 at 11:40 AM
To: GamesThatWork/BrushUpBuilds ***@***.***>
Cc: Deeksha Nemawarkar ***@***.***>, Author ***@***.***>
Subject: Re: [GamesThatWork/BrushUpBuilds] Sign up and account setup (Issue #5)

i appreciate your frustration and do not want to add to it,
but let me try to understand enough to address the problem.

iOS 17.3 i think, right?

but

are you signing up "with google"
or "with email"

how far does it get?
did y9ou try guest mode or phone mode (just curious)

THANKS

**Comment by DovJacobson** [comment]
to recap:

  email signup -- broken and removed until fixed
  google signup -- apparently broken also, not removed
  phone signup - works okay
  guest mode -- insecure but no problems

**Comment by dnemaw** [comment]
Perfect!!


From: Dov Jacobson ***@***.***>
Date: Friday, March 1, 2024 at 12:31 PM
To: GamesThatWork/BrushUpBuilds ***@***.***>
Cc: Deeksha Nemawarkar ***@***.***>, Author ***@***.***>
Subject: Re: [GamesThatWork/BrushUpBuilds] Sign up and account setup (Issue #5)
to recap:

email signup -- broken and removed until fixed
google signup -- apparently broken also, not removed
phone signup - works okay
guest mode -- insecure but no problems

**Comment by DovJacobson** [comment]
Problematic email, google, and guest authentication gateways are removed (email/google) or locked (guest)


@ernstc2:  If this issue is now cured,  please CLOSE it
