### ISSUE TITLE
Fullscreen Myscreen

### ISSUE THREAD

**Issue by ernstc2** [GamesThatWork/BrushUpBuilds#50]
**Describe the bug**
When going into the shop, regardless of being already in fullscreen on the home page. traveling to the shop will force the user out of fullscreen.

**To Reproduce**
1. Go into fullscreen on the home page
2. Go to shop
3. See screen not in fullscreen

**Expected behavior**
going to the shop should not force the user out of fullscreen

**Screenshots**
![full](https://github.com/GamesThatWork/BrushUpBuilds/assets/112519347/82f18e07-caa1-4ff9-abd5-bdc66ea64a26)
![out](https://github.com/GamesThatWork/BrushUpBuilds/assets/112519347/09afe6ec-e359-492a-8657-dc68123a1018)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [BUILD 0.444a]

**Additional context**
Windows issue

**Comment by DovJacobson** [comment]
Unfortunately, in some cases, this will be true until the app is a real single page

@ernstc2  is this true:
1- when playing the **installed** pwa app?
2- when playing on **iPhone**?
3- when playing on **iPhone after A2HS**?

**Comment by ernstc2** [comment]
Can confirm that this specific issue does not naturally occur on iPhones with the stats below.
What is A2HS? @DovJacobson 

**Smartphone (please complete the following information):**
 - Device: [Iphone 11]
 - OS: [iOS17.3.1]
 - Browser [Chrome]
 - Version [BUILD 0.444a]

**Comment by ernstc2** [comment]
issue on private repo
