### ISSUE TITLE
Pricing Best Deal Icon

### ISSUE THREAD

**Issue by ernstc2** [GamesThatWork/BrushUpBuilds#53]
**Describe the bug**
When on the "Pricing" page, an icon in orange says "BEST DEAL" above the buy option. While beautifully made, the icon overlaps with the child icon on the top right of the screen and realistically should be centered around the buy option or at least closer. 

**To Reproduce**
1. Go to "Pricing" page
2. See the overlap in the top right

**Expected behavior**
Hopefully would be right above or next to the buy option at the bottom. Refer to the screenshot below.

**Screenshots**
![Capture](https://github.com/GamesThatWork/BrushUpBuilds/assets/112519347/d1b25ae1-5579-4ab2-952a-bb9db390d2ac)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [BUILD 0.444a]

**Comment by DovJacobson** [comment]
fixed in 459

**Comment by ernstc2** [comment]
fixed in 0.459
