### ISSUE TITLE
Falling Numbers In Phone Shop

### ISSUE THREAD

**Issue by ernstc2** [GamesThatWork/BrushUpBuilds#54]
**Describe the bug**
When navigating through themes and rooms on my phone, I noticed prizes sometimes have cost labels with numbers that appear farther down vertically than expected. Refer to the screenshot below.

**To Reproduce**
1. Go to shop on phone
2. See error in multiple themes

**Expected behavior**
The costs for prizes should be centered with the slots visually.

**Screenshots**
![IMG_6348](https://github.com/GamesThatWork/BrushUpBuilds/assets/112519347/a04d765c-b649-4669-842e-5af9bc5539b4)

**Smartphone (please complete the following information):**
 - Device: [Iphone 11]
 - OS: [iOS17.3.1]
 - Browser [Chrome]
 - Version [BUILD 0.444a]

**Additional context**
This bug occurs nearly on every theme and doesn't seem to require any steps to make happen.

**Comment by DovJacobson** [comment]
@ernstc2 I do not see the error you refer to. 
The price tags are where I expect them to be.
Please draw on the screenshot to show what _you_ expected to see.

**Comment by ernstc2** [comment]
![yes](https://github.com/GamesThatWork/BrushUpBuilds/assets/112519347/1967c2ee-137d-4e68-80a1-a2b8806a20bf)

See how the number isn't centered, but is it below just a bit?

**Comment by DovJacobson** [comment]
447: In the current build, no labels are multi-line

**Comment by ernstc2** [comment]
Unfortunately with version 0.449, everything related to this problem has gotten far worse, see the shot below:

![IMG_6370](https://github.com/GamesThatWork/BrushUpBuilds/assets/112519347/a7927a13-436a-47b4-b298-6e0246bea377)

**Comment by DovJacobson** [comment]
@ernstc2  
I do not see these errors at all in various resolutions

1. Do you see the problem on v450?
2. Do you see on iPhone?
3. Do you see in windows/Chrome?

**Comment by DovJacobson** [comment]
very hard to fix a problem you can't see

**Comment by ernstc2** [comment]
@DovJacobson This is a problem I only see on my phone, even still on version 0.451

**Comment by ernstc2** [comment]
issue on private repo
