### ISSUE TITLE
Foreign Object Visible During Budd's "Attract Loop" Dance

### ISSUE THREAD

**Issue by ernstc2** [GamesThatWork/BrushUpBuilds#57]
**Describe the bug**
When on desktop and in the home screen before the screen is maximized, a weird object can be seen under BUDD.

**To Reproduce**
1. Be in home screen 
2. Be in a non-maximized window on desktop

**Expected behavior**
No strange objects

**Screenshots**
![1](https://github.com/GamesThatWork/BrushUpBuilds/assets/112519347/0742e3f2-1cb9-499d-8df7-d8ae3ba85758)
![2](https://github.com/GamesThatWork/BrushUpBuilds/assets/112519347/ecc1a781-1c3e-46d7-91be-0a7d851a687b)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [BUILD 0.444a]

**Additional context**
Not a high priority, just an abnormality.

**Comment by DovJacobson** [comment]
it is his golden toothbrush

**Comment by DovJacobson** [comment]
fixed in 461
Probably not worth the hacking required!!

**Comment by ernstc2** [comment]
still present in 463c

**Comment by ernstc2** [comment]
issue on private repo
