### ISSUE TITLE
Phone Screen Size Manipulation

### ISSUE THREAD

**Issue by ernstc2** [GamesThatWork/BrushUpBuilds#58]
Users currently while in the shop can manipulate their screens. This behavior only occurs in the prize shop.

Below are some screenshots of when users continuously double-tap their screen:

![1](https://github.com/GamesThatWork/BrushUpBuilds/assets/112519347/e8e1ba5b-4628-454c-a15b-1c1b938757aa)
![2](https://github.com/GamesThatWork/BrushUpBuilds/assets/112519347/6c15a099-8e31-4a21-8c5e-8dc0e8f48c1d)
![3](https://github.com/GamesThatWork/BrushUpBuilds/assets/112519347/6759d5fb-c08d-4147-ad65-4ce39d566fdf)

**Comment by DovJacobson** [comment]
@ernstc2 
users should NOT be able to resize the screen,
*pinch* and *spread* should be disabled by page directives that the iPhone is supposed to respect.

(1) Do you know what the default doubletap response is in safari or the iPhone OS?
(2) Does the misbehavior occur the Brushing Session and Match Game or only in the Prize Shop?
(3) Does the unwanted resize behavior in the Prize Shop include responding to Pinch & Spread?

**Comment by DovJacobson** [comment]
448 disabled double tap soom in shop and main game 
does this help?
does it have bad side effects?

**Comment by ernstc2** [comment]
fixed
