### ISSUE TITLE
Settings button

### ISSUE THREAD

**Issue by dnemaw** [GamesThatWork/BrushUpBuilds#6]
The settings button is too small to navigate. When clicked, it doesn't take you to another window and gets stuck.

**Comment by DovJacobson** [comment]
Thansk for this note
Which settings button?   
do you mean the one in the home page that has a grey simple cartoon face and maybe says "Guest #883773"
or similar

or do  you mean the one shaped like a gear?
or?

**Comment by dnemaw** [comment]
Yes, I mean the setting button shaped like a gear.

From: Dov Jacobson ***@***.***>
Date: Friday, March 1, 2024 at 11:43 AM
To: GamesThatWork/BrushUpBuilds ***@***.***>
Cc: Deeksha Nemawarkar ***@***.***>, Author ***@***.***>
Subject: Re: [GamesThatWork/BrushUpBuilds] Settings button (Issue #6)

Thansk for this note
Which settings button?
do you mean the one in the home page that has a grey simple cartoon face and maybe says "Guest #883773"
or similar

or do you mean the one shaped like a gear?
or?

**Comment by DovJacobson** [comment]
The one that opens the individual Childress settings when you are
![Screenshot 2024-03-01 125353](https://github.com/GamesThatWork/BrushUpBuilds/assets/74909114/327ceccd-0d0c-41b7-85b0-b0f3cdac02f8)
 on the ACCOUNT PAGE? (see attached)![Screenshot 2024-03-01 125353](https://github.com/GamesThatWork/BrushUpBuilds/assets/74909114/327ceccd-0d0c-41b7-85b0-b0f3cdac02f8)

this is .411 and it looks a l;ittle different than .409

**Comment by DovJacobson** [comment]
Changed size, image and functionality of button in question
