### ISSUE TITLE
Rotation in shop

### ISSUE THREAD

**Issue by ernstc2** [GamesThatWork/BrushUpBuilds#60]
**Describe the bug**
When in the shop, if the user flips into portrait mode for just long enough (only a few seconds), the screen will turn completely black in portrait mode and when the user eventually flips back to landscape the shop returns with a bugged slider, this bugged slider stays on this page and doesn't fix itself making it so the user cannot go to any other rooms. See the screenshots below.

**To Reproduce**
1. Go to the prize shop
2. Rotate screen until black (about 1-2 seconds)
3. rotate back
4. see bugged shop

**Expected behavior**
Hopefully, the shop would correctly correct itself

**Screenshots**
![IMG_6363](https://github.com/GamesThatWork/BrushUpBuilds/assets/112519347/1ba3357c-ac91-46df-8d29-00c21a6d6410)
![IMG_6364](https://github.com/GamesThatWork/BrushUpBuilds/assets/112519347/0c6c43c5-bf52-4021-9e8f-ca90c5beed3c)

**Smartphone (please complete the following information):**
 - Device: [Iphone 11]
 - OS: [iOS17.3.1]
 - Browser [Chrome]
 - Version [BUILD 0.444a]

**Additional context**
Initially thought to be related to issue #52  , however, is separate issue due to a bugged shop

**Comment by DovJacobson** [comment]
Please retest b/c this functionality was recently all rewritten and improved.

**Comment by ernstc2** [comment]
This seems to be fixed in 0460
