### ISSUE TITLE
Phone Black Border

### ISSUE THREAD

**Issue by ernstc2** [GamesThatWork/BrushUpBuilds#61]
**Describe the bug**
When on the phone app in the shop, black borders appear around the home button and around the user's total points star.

**To Reproduce**
1. Go to shop
2. See borders

**Expected behavior**
Like Windows app, borders shouldn't be there.

**Screenshots**
![1](https://github.com/GamesThatWork/BrushUpBuilds/assets/112519347/dac015b1-0dc4-44ab-8046-9f87e4ce106c)

**Smartphone (please complete the following information):**
 - Device: [Iphone 11]
 - OS: [iOS17.3.1]
 - Browser [Chrome]
 - Version [BUILD 0.444a]

**Additional context**
This bug is only apparent on the phone app, not on my Windows browser

**Comment by DovJacobson** [comment]
448 I think I found it (spurious css border setting)

**Comment by ernstc2** [comment]
These borders are now gone in version 0.449
