### ISSUE TITLE
No sound

### ISSUE THREAD

**Issue by ernstc2** [GamesThatWork/BrushUpBuilds#62]
**Describe the bug**
On Build 0.446, I currently have no sound on the testing server. This is applied to all pages of the app, including shop and brushing with Budd

**To Reproduce**
1. Go to any page
2. Dont hear anything

**Expected behavior**
User should hear things 😄 

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [BUILD 0.446]

**Additional context**
I say Build 0.446 on test server, even though test server says 0.445 on home screen.

**Comment by DovJacobson** [comment]
@ernstc2  Please retest with current build

**Comment by ernstc2** [comment]
Tested with build 0.449, can confirm this is a prominent issue

**Comment by DovJacobson** [comment]
fixed in 453

**Comment by ernstc2** [comment]
Fixed in 453
