### ISSUE TITLE
The child profile information not saving to my account.

### ISSUE THREAD

**Issue by jcorack** [GamesThatWork/BrushUpBuilds#7]
**Describe the bug**

The child profile information (Name, DOB, Gender, handiness) does not save to my account. 

**To Reproduce**
1. Go to 'https://bu-pwa.web.app/'
2. Click on 'bubble icon for child profile - enter name, birthday, gender and handiness' (my gmail account is still signed in automatically when I access the link in step 1. 
3. Brush teeth with bud.
4. Return to home page - 'no name' and no information in the profile. 

**Expected behavior**
The profile information for the child/user should save to the account.

**Smartphone (please complete the following information):**
 - Device: [google pixel 7 pro] 
 - OS: [android version 14]
 - Browser [google chrome]
 - Version [122.0.6261.90]
 

**Additional context**
-The app was downloaded to the phone via the chrome browser.

**Comment by DovJacobson** [comment]
Thank you for EXXCELLENT bug report

I think It is fixed now
@jcorack  or  @jon-dameron please verify & close

**Comment by DovJacobson** [comment]
apparently fixed (see above)
