### ISSUE TITLE
Match Game No Images of Budd

### ISSUE THREAD

**Issue by ernstc2** [GamesThatWork/BrushUpBuilds#71]
**Describe the bug**
The game images for the match game after brushing are missing. (Build 0.453)

**To Reproduce**
1. Go to the Brushing game
2. Wait for match game
3. See the lack of images of Budd

**Expected behavior**
The images of Budd show certain acts of brushing should appear here.

**Screenshots**
![Capture](https://github.com/GamesThatWork/BrushUpBuilds/assets/112519347/d2979873-071d-4830-b846-0e62c0b27d5d)
![2](https://github.com/GamesThatWork/BrushUpBuilds/assets/112519347/01eefe4a-9ced-4100-bc28-37eb36c23df8)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [BUILD 0.452]

**Comment by DovJacobson** [comment]
@ernstc2 was this regression tested in 454?

**Comment by ernstc2** [comment]
@DovJacobson Yes

**Comment by ernstc2** [comment]
fixed in 457
