### ISSUE TITLE
Phone Buttons No Interaction

### ISSUE THREAD

**Issue by ernstc2** [GamesThatWork/BrushUpBuilds#72]
**Describe the bug**
Currently on build 0.454, while using the app on a phone, all buttons on the home screen become completely un-interactable, basically hard locking the user on the home screen.

**To Reproduce**
1. Go to the website on a phone
2. Try to click on any button

**Screenshots**
![IMG_6395](https://github.com/GamesThatWork/BrushUpBuilds/assets/112519347/3fc1d10c-ab98-4d8e-9c31-6b13fa8af22c)
![IMG_6396](https://github.com/GamesThatWork/BrushUpBuilds/assets/112519347/be907519-ba04-452a-a036-8f93947a88df)

**Smartphone (please complete the following information):**
 - Device: [Iphone 11]
 - OS: [iOS17.3.1]
 - Browser [Chrome]
 - Version [BUILD 0.454]

**Comment by DovJacobson** [comment]
@ernstc2 Please clarify -  are buttons nonresponsive
          in the first screenshot (home screen), 
          in the second (auth screen) - 
          or both.

**Comment by ernstc2** [comment]
On both screens the buttons are unresponsive, the first screenshot shows a page where I was already signed into and none of the buttons were interactable, to further test I went into a private window and tried to interact with the buttons for sign up and none of those were interactable. in both cases buttons were unresponsive. @DovJacobson

**Comment by DovJacobson** [comment]
@ernstc2 This bug is addressed in v 456+


**Please note:**
 - this is likely to re-open the iPhone double-tap zoom issue

**Comment by ernstc2** [comment]
fixed in version 0.457
