### ISSUE TITLE
Title Screen Bud not Centered

### ISSUE THREAD

**Issue by ernstc2** [GamesThatWork/BrushUpBuilds#73]
**Describe the bug**
When on the home screen seeing Budd dance, I've noticed that either he's not centered or the bubble where he's in is not.

**Screenshots**
![IMG_6395](https://github.com/GamesThatWork/BrushUpBuilds/assets/112519347/1a86e10c-9b09-477a-8944-d563c87c2e34)
![1](https://github.com/GamesThatWork/BrushUpBuilds/assets/112519347/2df0fb08-c0cf-4b0e-baa5-905839c0dcc2)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [BUILD 0.454]

**Comment by DovJacobson** [comment]
I am not sure what the problem is?
The overlap of the title and the bubble is an intentional design choice,
and so is the framing of Budd within the bubble (eyes about 2/3 up, feet out of frame)
Maybe I am missing something?

**Comment by ernstc2** [comment]
![3](https://github.com/GamesThatWork/BrushUpBuilds/assets/112519347/6bb4c614-beb1-44de-b28e-71a778ceae09)

I might be imagining things but I hope this red line I drew through the circle helps convey what I mean.

**Comment by ernstc2** [comment]
issue on private repo
