### ISSUE TITLE
After Prize Purchase Audio Error

### ISSUE THREAD

**Issue by ernstc2** [GamesThatWork/BrushUpBuilds#75]
**Describe the bug**
When in the shop, after an item is bought, if the user decides to switch themes a different audio is played than what is expected. Instead of the "click" sound it plays the "waa-waaaah" sound when switching themes. This bug stays true when even switching rooms and then continuing to switch themes.

**To Reproduce**
1. Go to the Prize shop
2. Purchase a prize
3. Switch themes
4. Hear audio error

**Expected behavior**
The standard clicking sound should play when switching themes, and audio should not play at unintended times.

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [BUILD 0.458]

**Additional context**
The bug resets when the user goes back to the home page.

**Comment by DovJacobson** [comment]
cannot yet reproduce this at all
may be fixed in 459

**Comment by ernstc2** [comment]
still present in 0.459

**Comment by ernstc2** [comment]
issue on private repo
