### ISSUE TITLE
Theme refreash

### ISSUE THREAD

**Issue by ernstc2** [GamesThatWork/BrushUpBuilds#77]
**Describe the bug**
When in the prize shop and messing around with themes, if the user ever clicks on the room they already reside in, the themes will play animations with a parie4d sound of them refreshing or re-appearing. however, when the user is already in the room view seeing what they already own, if the user presses the room again to cause this refresh to happen again the sound will occur but no animation to the themes. For clarity, below I've put instructions for what the normal animation + sound looks like and the replication of this bug.

**To Reproduce**(BUG)
1. Go to the Prize shop
2. Click on the starter room
3. click on the starter room again
4. Hear animation sound with no update

**To Reproduce**(NORMAL BEHAVIOR)
1. Go to the Prize shop
2. Click on the starter room
3. Click on any theme
4. Click back to the room view
5. Hear and see animation sound with visual update

**Expected behavior**
hopefully, the user would see the animation always, not just the sound when already in the starter room

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [BUILD 0.458]

**Additional context**
Screenshots aren't very helpful in explaining this bug, as it pertains to sounds and animations, not stand-still issues.

**Comment by DovJacobson** [comment]
e3ohffghoh

**Comment by ernstc2** [comment]
issue on private repo
