### ISSUE TITLE
Phone Shop Sounds Missing

### ISSUE THREAD

**Issue by ernstc2** [GamesThatWork/BrushUpBuilds#78]
**Describe the bug**
Currently, on build 0.458, all in-prize shop sounds are missing while playing on the phone except for the "wobble" animation sound. All noticeable missing sounds include: (ALL) slider sounds, themes appearing sounds, confirm buy sounds, clicking from theme to theme sound, and possibly more.

**To Reproduce**
1. Go to prize shop on phone
2. Click from theme to theme
3. Notice missing sounds

**Smartphone (please complete the following information):**
 - Device: [Iphone 11]
 - OS: [iOS17.3.1]
 - Browser [Chrome]
 - Version [BUILD 0.458]

**Additional context**
Again not all sounds are gone because I can still hear the wobble animation sounds.

No screenshots provided as this is a sound issue.

**Comment by DovJacobson** [comment]
459 sounds revamped and now seem to be working better

**Comment by ernstc2** [comment]
still present in 0.459

**Comment by ernstc2** [comment]
issue on private repo
