### ISSUE TITLE
App settings not accessible

### ISSUE THREAD

**Issue by jcorack** [GamesThatWork/BrushUpBuilds#8]
**Describe the bug**
The app settings are not accessible. Meaning that nothing happens when the gear icon is clicked. 

**To Reproduce**
1. Open the app.
2. Click on the settings 'gear' icon.

**Expected behavior**
The settings window should open. 

**Smartphone (please complete the following information):**
 - Device: [google pixel 7 pro] 
 - OS: [android version 14]
 - Browser [google chrome]
 - Version [122.0.6261.90]

**Additional context**
-The app was downloaded to the phone via the chrome browser.

**Comment by jcorack** [comment]
Ah, I see. You are correct. The settings window does appear if I click on the account icon. 

I was previously attempting to select the little gear circle next to the account circle icon. The gear icon does get highlighted, which made it seem like it was an active 'button'. 

I attached a screenshot.

![Screenshot_20240305-131625](https://github.com/GamesThatWork/BrushUpBuilds/assets/162374421/d0a69da2-2ee2-4c52-8d13-e91c318a58a2)

**Comment by DovJacobson** [comment]
see   above
