### ISSUE TITLE
Stuck on loading app (phone only)

### ISSUE THREAD

**Issue by ernstc2** [GamesThatWork/BrushUpBuilds#80]
**Describe the bug**
Currently on 0.463c, when trying to load the app on a phone the user becomes stuck on the screen shown in the screenshot below. To un-stuck themselves the user has to refresh the page which is impossible once the user has added the app to their home screen.

**To Reproduce**
1. Open app on phone device
2. endlessly wait

**Expected behavior**
the user should be asked for camera privileges and then see dancing Bud.

**Screenshots**
![IMG_6540](https://github.com/GamesThatWork/BrushUpBuilds/assets/112519347/ad71e509-d4d8-447d-be7b-8a223e6d7ace)

**Smartphone (please complete the following information):**
 - Device: [Iphone 11]
 - OS: [iOS17.3.1]
 - Browser [Chrome]
 - Version [BUILD 0.463c]

**Comment by DovJacobson** [comment]
what is 463c?
is there a single build with that number?
do i need to build it - or is deployed somewhere?

**Comment by ernstc2** [comment]
this is the current build that is pushed to main, as can be seen in test deployment
https://bu-pwa--chris-test-xpww0v5t.web.app/

**Comment by ernstc2** [comment]
issue on private repo
