### ISSUE TITLE
Orientation issue

### ISSUE THREAD

**Issue by dnemaw** [GamesThatWork/BrushUpBuilds#9]
We want to make sure that the app orientation defaults to the landscape mode. 
Reasons-
- the app tends to freeze when the orientation is changed
- the screen is cut off and is displayed only on half screen

**Comment by DovJacobson** [comment]
the system now forces the screen to landscape mode on iPhone and Android
(this fix led to confusion when the orientaion is locked to portrait -- this is a separate issue)



@ernstc2:  If this issue is now cured,  please CLOSE it
